[kamaradi.csv]
id = "int"
nickname = "string"
fullname = "string"
vyska = "int"
bydliste = "string"

[mesta.csv]
name = "string"
vzdalenost_od_prahy = "int"
datum_zalozeni = "datetime" # todo

[test.csv]
column1 = "string"
column2 = "int"

[x.csv]
name = "string"

r[y.csv]
surname = "string"


#[*_info.csv]
#anything = "string"

